POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Nir Mezamer",
    "Dog": "Dino",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Nir Mezamer",
    "Dog": "Dino",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "12:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Guy Shpigler",
    "Dog": "Oren",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/RemoveJob
Content-Type: application/json

{
    "Owner": "Guy Shpigler",
    "Dog": "Oren",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

GET http://localhost:7071/api/GetAllJobs/Guy_Shpigler

###

GET http://localhost:7071/api/GetAllJobs


###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "PartitionKey": "Guy Shpigler",
    "RowKey": "1",
    "Address": "Pichman",
    "AppartmentNumber": 7,
    "City": "Tel Aviv",
    "Date": "1",
    "Dog": "Sheleg",
    "Duration": "2024-08-02T21:30:00.000Z",
    "HouseNumber": 5,
    "Owner": "Guy Shpigler",
    "Phone": "+972505467771",
    "Time": "2024-08-03T06:00:00.000Z"
}

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "PartitionKey": "Nir Mezamer",
    "RowKey": "1",
    "Address": "Nachmani",
    "AppartmentNumber": 7,
    "City": "Tel Aviv",
    "Date": "1",
    "Dog": "Dino",
    "Duration": "2024-08-02T21:30:00.000Z",
    "HouseNumber": 17,
    "Owner": "Nir Mezamer",
    "Phone": "+972523864475",
    "Time": "2024-08-03T07:00:00.000Z"
}