POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Nir Mezamer",
    "Dog": "Dino",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Nir Mezamer",
    "Dog": "Dino",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "12:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "Owner": "Guy Shpigler",
    "Dog": "Oren",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

POST http://localhost:7071/api/RemoveJob
Content-Type: application/json

{
    "Owner": "Guy Shpigler",
    "Dog": "Oren",
    "City" : "Tel Aviv",
    "Address" : "Hertzel",
    "HouseNumber" : "1",
    "AppartmentNumber" : "1",
    "Phone" : "+972501234567",
    "Date": "01-09-2024",
    "Time": "10:00",
    "Duration": "00:30"
}

###

GET http://localhost:7071/api/GetAllJobs/Guy_Shpigler

###

GET http://localhost:7071/api/GetAllJobs
