POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "PartitionKey": "Jobs",
    "RowKey": "1",
    "Owner": "Nir Mezamer",
    "DogName": "Dino",
    "startDate": "01-09-2024",
    "startTime": "10:00",
    "endDate": "01-09-2024",
    "endTime": "12:00"
}


###

GET http://localhost:7071/api/ReadCounter

###

GET http://localhost:7071/api/IncreaseCounter

###

POST http://localhost:7071/api/InsertJob
Content-Type: application/json

{
    "PartitionKey": "Jobs",
    "RowKey": "2",
    "Owner": "Guy Shpigler",
    "DogName": "Oren",
    "startDate": "01-09-2024",
    "startTime": "10:00",
    "endDate": "01-09-2024",
    "endTime": "12:00"
}

###

POST http://localhost:7071/api/RemoveJob
Content-Type: application/json

{
    "PartitionKey": "counters",
    "RowKey": "counter_0"
}

###

GET http://localhost:7071/api/GetAllJobs
